In [129]:
# Main
import numpy as np
from scipy import stats
import pandas as pd

# Visualizations
import matplotlib.pyplot as plt
import seaborn as sns

# Split and Cross Val
from sklearn.model_selection import train_test_split, GridSearchCV

# Preprocess and Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Models
from sklearn.linear_model import LinearRegression, LogisticRegression, Ridge, Lasso, RidgeCV, LassoCV
from sklearn.svm import SVC
from sklearn.cluster import KMeans

# Ensemble Models
from sklearn.ensemble import RandomForestRegressor, GradientBoostingClassifier, RandomForestClassifier
from xgboost import XGBRegressor, XGBClassifier

# Metrics
from sklearn.metrics import (mean_absolute_error, 
                             accuracy_score, 
                             root_mean_squared_error, 
                             r2_score, 
                             mean_absolute_error,
                             mean_squared_error, 
                             silhouette_score)

# Environments and serialization
import joblib

# Datasets
from sklearn.datasets import load_diabetes

In [130]:
heavy_df = pd.read_csv('data/spacex_web_scraped.csv')

In [131]:
heavy_df.head()

,Flight No.,Launch site,Payload,Payload mass,Orbit,Customer,Launch outcome,Date,Time,Version Booster,Booster landing
0,1,Cape Canaveral,Dragon Spacecraft Qualification Unit,U,LEO,SpaceX,Success,4 June 2010,18:45,F9v1.0,Failure (parachute)
1,2,Cape Canaveral,SpaceX COTS Demo Flight 1,U,LEO,NASA,Success,8 December 2010,15:43,F9v1.0,Failure (parachute)
2,3,Cape Canaveral,SpaceX COTS Demo Flight 2,525 kg,LEO,NASA,Success,22 May 2012,07:44,F9 v1.0,No attempt
3,4,Cape Canaveral,SpaceX CRS-1,"4,700 kg",LEO,NASA,Success,8 October 2012,00:35,F9 v1.0,No attempt
4,5,Cape Canaveral,SpaceX CRS-2,"4,877 kg",LEO,NASA,Success,1 March 2013,15:10,F9 v1.0,No attempt

In [132]:
heavy_df['Year']= heavy_df['Date'].str.slice(-4).astype(int)

In [133]:
heavy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 612 entries, 0 to 611
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Flight No.       612 non-null    int64
 1   Launch site      612 non-null    object
 2   Payload          609 non-null    object
 3   Payload mass     612 non-null    object
 4   Orbit            610 non-null    object
 5   Customer         598 non-null    object
 6   Launch outcome   612 non-null    object
 7   Date             612 non-null    object
 8   Time             612 non-null    object
 9   Version Booster  612 non-null    object
 10  Booster landing  612 non-null    object
 11  Year             612 non-null    int64
dtypes: int64(2), object(10)
memory usage: 57.5+ KB

In [134]:
heavy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 612 entries, 0 to 611
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Flight No.       612 non-null    int64
 1   Launch site      612 non-null    object
 2   Payload          609 non-null    object
 3   Payload mass     612 non-null    object
 4   Orbit            610 non-null    object
 5   Customer         598 non-null    object
 6   Launch outcome   612 non-null    object
 7   Date             612 non-null    object
 8   Time             612 non-null    object
 9   Version Booster  612 non-null    object
 10  Booster landing  612 non-null    object
 11  Year             612 non-null    int64
dtypes: int64(2), object(10)
memory usage: 57.5+ KB

In [135]:
heavy_df['Launch outcome'].value_counts()

Launch outcome
Success    610
Failure      2
Name: count, dtype: int64

In [136]:
heavy_df['Booster landing'].value_counts()

Booster landing
Success ( OCISLY           161
Success ( JRTI             121
Success ( ASOG             117
Success                     91
Success ( LZ‑1              38
Success ( LZ‑4              26
No attempt                  18
No attempt                   9
Success ( LZ‑2               7
Controlled (ocean)           6
Failure ( OCISLY             5
Failure ( JRTI               4
Failure (parachute)          2
Failure (ocean)              2
Failure ( LZ‑1               1
Success( JRTI                1
Precluded  (drone ship)      1
Failure ( ASOG               1
Success ( LZ‑40              1
Name: count, dtype: int64

In [137]:
heavy_df.head()

,Flight No.,Launch site,Payload,Payload mass,Orbit,Customer,Launch outcome,Date,Time,Version Booster,Booster landing,Year
0,1,Cape Canaveral,Dragon Spacecraft Qualification Unit,U,LEO,SpaceX,Success,4 June 2010,18:45,F9v1.0,Failure (parachute),2010
1,2,Cape Canaveral,SpaceX COTS Demo Flight 1,U,LEO,NASA,Success,8 December 2010,15:43,F9v1.0,Failure (parachute),2010
2,3,Cape Canaveral,SpaceX COTS Demo Flight 2,525 kg,LEO,NASA,Success,22 May 2012,07:44,F9 v1.0,No attempt,2012
3,4,Cape Canaveral,SpaceX CRS-1,"4,700 kg",LEO,NASA,Success,8 October 2012,00:35,F9 v1.0,No attempt,2012
4,5,Cape Canaveral,SpaceX CRS-2,"4,877 kg",LEO,NASA,Success,1 March 2013,15:10,F9 v1.0,No attempt,2013

In [138]:
heavy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 612 entries, 0 to 611
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Flight No.       612 non-null    int64
 1   Launch site      612 non-null    object
 2   Payload          609 non-null    object
 3   Payload mass     612 non-null    object
 4   Orbit            610 non-null    object
 5   Customer         598 non-null    object
 6   Launch outcome   612 non-null    object
 7   Date             612 non-null    object
 8   Time             612 non-null    object
 9   Version Booster  612 non-null    object
 10  Booster landing  612 non-null    object
 11  Year             612 non-null    int64
dtypes: int64(2), object(10)
memory usage: 57.5+ KB

In [139]:
heavy_df.sample()

,Flight No.,Launch site,Payload,Payload mass,Orbit,Customer,Launch outcome,Date,Time,Version Booster,Booster landing,Year
578,579,Vandenberg,Starlink,"~15,525 kg",LEO,SpaceX,Success,"December 14, 2025",05:49,F9B5,Success ( OCISLY,2025

In [142]:
heavy_df['Year'].value_counts(sort=False)

Year
2010      2
2012      2
2013      3
2014      6
2015      7
2016      8
2017     18
2018     20
2019     11
2020     26
2021     31
2022     60
2023     88
2024    135
2025    165
2026     30
Name: count, dtype: int64